version: '3.4'

services:
  ahegao:
    image: ${DOCKER_REGISTRY-}ahegao
    build:
      context: .
      dockerfile: Ahegao/Dockerfile

    volumes:
      - G:\Hentai:/app/downloads/

    labels:
      - "traefik.http.routers.ahegao.rule=Host(`ahegao.docker.localhost`)"


    networks:
      - default
      - login

networks:
  default:
    external:
      name: gateway

  login:
    external:
      name: login